#!/bin/bash
j=07;
h=2017;
cd ..;
for i in {25..31};
do
cd $j$i$h
scp -r GT.mat 10.24.250.249:/media/vahid/96CC807ACC805701/Agronomy/modifiedCode/DataAfterMeeting/groundTruth/$j$i$h/.
cd ..;
done
j=08;
for i in {01,02,04,06,09,11,15,18,22,30};
do
cd $j$i$h;
scp -r GT.mat 10.24.250.249:/media/vahid/96CC807ACC805701/Agronomy/modifiedCode/DataAfterMeeting/groundTruth/$j$i$h/.
cd ..;
done

j=09;
i=08;
cd $j$i$h;
scp -r GT.mat 10.24.250.249:/media/vahid/96CC807ACC805701/Agronomy/modifiedCode/DataAfterMeeting/groundTruth/$j$i$h/.
cd ..$h;

