function parSave(result_path,picName,images_folder,thickness,binary,skel,starting_point,yellow_minor,...
    yellow_rotation,long_path,tip,graph,end_points,entire_objects_with_endpoints,WithoutLongestpath,sendToBP,...
    branch_points,branching_zone1,branching_zone,branching_zone_path,central_path,central_length,tassel_path,...
    length_tassel,centralAreaDensityTemp,circleDensityVarTemp,first_path,first_length,second_path,second_length,...
    first_angle,second_angle)


save(strcat(result_path,'/matFiles/',strtok(images_folder(picName).name,'.'),'.mat'), ...
    'result_path','picName','images_folder','thickness','binary','skel','starting_point','yellow_minor',...'
    'yellow_rotation','long_path','tip','graph','end_points','entire_objects_with_endpoints','WithoutLongestpath',...
    'sendToBP','branch_points','branching_zone1','branching_zone','branching_zone_path','central_path','central_length',...
    'tassel_path','length_tassel','centralAreaDensityTemp','circleDensityVarTemp','first_path','first_length',...
    'second_path','second_length','first_angle','second_angle','-v7.3');

save(strcat(result_path,'/matFilesForChecking/',strtok(images_folder(picName).name,'.'),'.mat'), ...
    'binary','skel','yellow_minor','long_path','graph','WithoutLongestpath','-v7.3');

end